.TH "JAMES TOMASINO" 1 "29 August 2020" "2020.08.29"

.SH NAME
james_tomasino \- developer, writer, table-top gamer, world traveller

.SH SYNOPSIS
.B james_tomasino
[-aeiou]
.P

.SH DESRIPTION
.B "James Tomasino"
does things on the internet. He administers several communities on the
.B tildeverse
and works as a freelance developer and digital marketing strategist, especially
in Pharamceutical advertising. He also enjoys writing both fiction and
non-fiction and does so prolifically on the http, gopher, and gemini protocols.
.PP
James Tomasino can be found in many of the following places
.TP
.B "The Tildeverse"
https://cosmic.voyage and https://tilde.black are both tilde communities he
administers. They're free to join.
.TP
.B "Professional Stuff"
There's plent of work here on Github, but the vast majority is in private
repositories. Much of the work in the last decade has been for pharmaceutical
companies either in website, banner, email, conference panels, or digital sales
aid form. In the past he has built applications on a number of platforms. If your
professional needs touch digital marketing he's probably experienced with
it.
.TP
.B "Social things"
He spends a great deal of time in IRC over at
.B irc.tilde.chat
and 
.B freenode.net.
He's also on the Fediverse at
.B @tomasino@tilde.zone
, but the safest way to find him online is to refer to the links on
.B https://tomasino.org.

.SH EXIT STATUS
The
.B "James Tomasino"
exits with a 0 code on success, a 42 if discovering the answer to the great
question of life the universe and everything, 216 is being asked the sum of the
72 hidden names of God, and >0 if an error occurs.

.SH EXAMPLES
.TP
.B james_tomasino
Answers, `Hello!'
.TP
.B james_tomasino -a
The sound he makes when falling from a great height
.TP
.B james_tomasino -e
Useful when encountering an unexpected spider in the bathroom
.TP
.B james_tomasino -i
He thinks, therefore he is
.TP
.B james_tomasino -o
Realization and understanding of a great hidden truth
.TP
.B james_tomasino -u
When someone gets a really good burn in

.SH LICENSE
Schrödinger License r3
.TP
.B https://github.com/benlk/misc-licenses/blob/master/schrodinger-license.md

.SH BUGS
There are probably lots of problems with James Tomasino. If you can't hold your
tongue about them and need to call them out, I guess you can report issues at
the git repositories at
.B https://github.com/jamestomasino

.SH AUTHOR
James Tomasino <github (at) jamestomasino (dot) com>
